# secrets management via .env (excluded via .gitignore)
dotenv: .env

project_structure:
    scripts: test_brownie
    tests: test_brownie

networks:
    default: development
    mainnet-fork:
        cmd_settings:
            accounts: 20
    development:
        gas_price: 1 # (1 wei)
        cmd_settings:
            # without this explicit setting chainid==1 is returend by block.chainid
            accounts: 20
            chain_id: 1337

# brownie default values made explicit
compiler:
    evm_version: null
    solc:
        # version: 0.8.22
        # optimizer:
        #     enabled: true
        #     runs: 200
        # # https://eth-brownie.readthedocs.io/en/stable/compile.html#compiler-settings
        remappings:
            - "@openzeppelin5=OpenZeppelin/openzeppelin-contracts@5.0.0"
            - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.3"
            - "@openzeppelin-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.3"

# packages below will be added to brownie
# you may use 'brownie pm list' after 'brownie compile' 
# to list the packages installed via the dependency list below
dependencies:
    # **Important**: If you update any version here, please also update them in .vscode/settings.json section 'solidity.remappingsUnix'
    # github dependency format: <owner>/<repository>@<release>
    - OpenZeppelin/openzeppelin-contracts@5.0.0
    - OpenZeppelin/openzeppelin-contracts@4.9.3
    - OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.3
