@startuml

package "Product Module" as productModule {
  [Product] as product
}

[PricingService] as pricingS
[ComponentService] as componentS
[RiskService] as riskS
[ApplicationService] as applicationS
[PolicyService] as policyS
[ClaimService] as claimS


componentS <-- product
riskS <-- product
pricingS <- product

product --> applicationS
product --> policyS
product -> claimS

@enduml