@startuml

object Protocol
object "Registry (global)" as gr
object "Registry (chain)" as cr
object Service
object Staking
object Instance

object Product
object Distribution
object Oracle
object Pool

object Policy
object Distributor
object Bundle

Protocol *-- "1" gr
gr *-- "n" cr

Service "n" -* cr
cr *- "1" Staking
cr *-- "n" Instance

Instance *-- "n" Product
Product *-- "n" Distribution
Product *-- "n" Oracle
Product *-- "n" Pool

Policy "n" -* Product
Distributor "n" -* Distribution
Distribution -[hidden]> Oracle
Pool *- "n" Bundle

@enduml