name: Bug Report
description: File a bug report and have a chance to claim our bug bounty
title: "[Bug]: "
labels: ["bug", "bug bounty"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        By submitting the bug, you will participate in our [bug bounty program](https://github.com/etherisc/depeg-ui/wiki/Bug-Bounty-Program) and have the chance to earn some DIP. 
        In case your bug gets accepted (in this case we will add the label _accepted_ to the issue) and you are eligible for the bug bounty, we'll notify you how you will receive the bounty. 
        Please **do not change any of the preselected labels or assignees**.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: |
        Also tell us, what did you expect to happen? If possible, please provide screenshots (drag and drop images into the text area) and the date and time the problem occured. 
        Additionally, if you the bug was encountered while interacting with a wallet (e.g. while buying a policy), please provide the wallet address you used. 
        And any other data you think will help us to reproduce the bug. The more details we have, the better we can figure out what went wrong.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: operating-system
    attributes:
      label: What operating system are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Mac OS
        - Linux
        - Android
        - iOS
        - Other (please mention in the description)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Brave
        - Other (please mention in the description)
    validations:
      required: true
  - type: dropdown
    id: wallet-extension
    attributes:
      label: What wallet extension are you using?
      multiple: true
      options:
        - Metamask
        - Rabby Wallet
        - WalletConnect
        - Other (please mention in the description)
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Rules
      description: By submitting this issue, you agree to follow our [Rules](https://github.com/etherisc/depeg-ui/wiki/Bug-Bounty-Program)
      options:
        - label: I agree to follow this project's rules
          required: true
  