version: '3'

services:
  anvil:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile.anvil
    volumes:
      - anvil-state:/anvil
    # ports:
    #   - "7545:7545"
  contracts:
    # See https://aka.ms/vscode-remote/containers/non-root for details.
    user: node
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: "1-20" 
    volumes:
      - ..:/workspaces/gif-next:cached
      #- gif-next-node_modules:/workspaces/gif-next/node_modules
      #- $HOME/.ssh/:/home/vscode/.ssh/ # Mount the ssh folder to authenticate with github
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

volumes:
  #gif-next-node_modules:
  anvil-state:
