# custom aliases for forge commands

alias fb='FOUNDRY_PROFILE=ci forge build'
alias fbw='FOUNDRY_PROFILE=ci forge build --watch'
alias fbc='FOUNDRY_PROFILE=ci forge build contracts/'
alias fbcw='FOUNDRY_PROFILE=ci forge build --watch contracts/'

alias ft='FOUNDRY_PROFILE=ci forge test'
# exclude all fuzz and continuous tests
alias ftf='FOUNDRY_PROFILE=ci forge test --nmt "testFuzz|test_continuous"'
alias ftmw='FOUNDRY_PROFILE=ci forge test -vvvv --watch --mt'
