# custom aliases for forge commands

alias fb='FOUNDRY_PROFILE=ci forge build'
alias fbw='FOUNDRY_PROFILE=ci forge build --watch'
alias fbc='FOUNDRY_PROFILE=ci forge build contracts/'
alias fbcw='FOUNDRY_PROFILE=ci forge build --watch contracts/'

alias ft='FOUNDRY_PROFILE=ci forge test'
# exclude all fuzz and continuous tests
alias ftf='FOUNDRY_PROFILE=ci forge test --nmt "_longRunning"'
alias ftt='FOUNDRY_PROFILE=ci forge test -vvvv --mt'
alias fttg='FOUNDRY_PROFILE=ci forge test --gas-report --mt'
alias fttw='FOUNDRY_PROFILE=ci forge test -vvvv --watch --mt'
alias ftc='FOUNDRY_PROFILE=ci forge test -vvvv --mc'
alias ftcw='FOUNDRY_PROFILE=ci forge test -vvvv --watch --mc'
