name: Build and test (Hardhat)

on:
  push:
    branches: [main, develop]
    tags: '*'
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
    
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: NPM install
        run: npm install

      - name: Compile contracts
        run: npm run build

      - name: Run all tests
        run: npm run test
