name: Publish package to npmjs

on:
  workflow_run:
    workflows: 
      - build_hardhat.yml
      - build_foundry.yml
    types: 
      - completed

jobs:
  publish:
    name: Publish package to npmjs
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
    # only run if all tests were successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
