name: Publish package to npmjs

on:
  workflow_run:
    workflows: ["Build and test (Hardhat)", "Build and test (Foundry)"]
    types: [completed]

jobs:
  publish:
    name: Publish package to npmjs
    runs-on: ubuntu-latest
    permissions:
        contents: read
        id-token: write
    # only run if all tests were successful
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      # latest npm required for provenance
      - run: npm install -g npm
      - run: npm ci

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: "Build and test (Hardhat)"
          name: artifacts
          path: |
            artifacts

      - name: Set build version identifier
        # version is set to current patch + 1 and a build identifier (revision plus seconds to avoid duplicates) is added
        run: npm version "`npm version patch --no-git-tag-version`-`git rev-parse --short HEAD`-`date +%s | tail -c4`" --no-git-tag-version

      - run: npm publish --tag next --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_ACCESS_TOKEN }}
